/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RankingGestoresRouteImport } from './routes/ranking-gestores'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestoresRouteImport } from './routes/gestores'
import { Route as FarmaciasRouteImport } from './routes/farmacias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmaciasIndexRouteImport } from './routes/farmacias.index'
import { Route as FarmaciasIdRouteImport } from './routes/farmacias.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingGestoresRoute = RankingGestoresRouteImport.update({
  id: '/ranking-gestores',
  path: '/ranking-gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresRoute = GestoresRouteImport.update({
  id: '/gestores',
  path: '/gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasRoute = FarmaciasRouteImport.update({
  id: '/farmacias',
  path: '/farmacias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasIndexRoute = FarmaciasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmaciasRoute,
} as any)
const FarmaciasIdRoute = FarmaciasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FarmaciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasRouteWithChildren
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/ranking-gestores': typeof RankingGestoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/setup': typeof SetupRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/farmacias/': typeof FarmaciasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/ranking-gestores': typeof RankingGestoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/setup': typeof SetupRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/farmacias': typeof FarmaciasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasRouteWithChildren
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/ranking-gestores': typeof RankingGestoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRoute
  '/setup': typeof SetupRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/farmacias/': typeof FarmaciasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/farmacias'
    | '/gestores'
    | '/login'
    | '/ranking'
    | '/ranking-gestores'
    | '/relatorios'
    | '/reunioes'
    | '/setup'
    | '/farmacias/$id'
    | '/farmacias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/gestores'
    | '/login'
    | '/ranking'
    | '/ranking-gestores'
    | '/relatorios'
    | '/reunioes'
    | '/setup'
    | '/farmacias/$id'
    | '/farmacias'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/farmacias'
    | '/gestores'
    | '/login'
    | '/ranking'
    | '/ranking-gestores'
    | '/relatorios'
    | '/reunioes'
    | '/setup'
    | '/farmacias/$id'
    | '/farmacias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FarmaciasRoute: typeof FarmaciasRouteWithChildren
  GestoresRoute: typeof GestoresRoute
  LoginRoute: typeof LoginRoute
  RankingRoute: typeof RankingRoute
  RankingGestoresRoute: typeof RankingGestoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReunioesRoute: typeof ReunioesRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-gestores': {
      id: '/ranking-gestores'
      path: '/ranking-gestores'
      fullPath: '/ranking-gestores'
      preLoaderRoute: typeof RankingGestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores': {
      id: '/gestores'
      path: '/gestores'
      fullPath: '/gestores'
      preLoaderRoute: typeof GestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias': {
      id: '/farmacias'
      path: '/farmacias'
      fullPath: '/farmacias'
      preLoaderRoute: typeof FarmaciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias/': {
      id: '/farmacias/'
      path: '/'
      fullPath: '/farmacias/'
      preLoaderRoute: typeof FarmaciasIndexRouteImport
      parentRoute: typeof FarmaciasRoute
    }
    '/farmacias/$id': {
      id: '/farmacias/$id'
      path: '/$id'
      fullPath: '/farmacias/$id'
      preLoaderRoute: typeof FarmaciasIdRouteImport
      parentRoute: typeof FarmaciasRoute
    }
  }
}

interface FarmaciasRouteChildren {
  FarmaciasIdRoute: typeof FarmaciasIdRoute
  FarmaciasIndexRoute: typeof FarmaciasIndexRoute
}

const FarmaciasRouteChildren: FarmaciasRouteChildren = {
  FarmaciasIdRoute: FarmaciasIdRoute,
  FarmaciasIndexRoute: FarmaciasIndexRoute,
}

const FarmaciasRouteWithChildren = FarmaciasRoute._addFileChildren(
  FarmaciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FarmaciasRoute: FarmaciasRouteWithChildren,
  GestoresRoute: GestoresRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
  RankingGestoresRoute: RankingGestoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReunioesRoute: ReunioesRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
