/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestoresRouteImport } from './routes/gestores'
import { Route as FarmaciasRouteImport } from './routes/farmacias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmaciasIdRouteImport } from './routes/farmacias.$id'
import { Route as FarmaciasIndexRouteImport } from './routes/farmacias.index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresRoute = GestoresRouteImport.update({
  id: '/gestores',
  path: '/gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasRoute = FarmaciasRouteImport.update({
  id: '/farmacias',
  path: '/farmacias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasIdRoute = FarmaciasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FarmaciasRoute,
} as any)
const FarmaciasIndexRoute = FarmaciasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmaciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasRoute
  '/farmacias/': typeof FarmaciasIndexRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasIndexRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasRoute
  '/farmacias/': typeof FarmaciasIndexRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/gestores': typeof GestoresRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automacoes'
    | '/configuracoes'
    | '/farmacias'
    | '/farmacias/'
    | '/farmacias/$id'
    | '/gestores'
    | '/login'
    | '/relatorios'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automacoes'
    | '/configuracoes'
    | '/farmacias'
    | '/farmacias/$id'
    | '/gestores'
    | '/login'
    | '/relatorios'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/automacoes'
    | '/configuracoes'
    | '/farmacias'
    | '/farmacias/'
    | '/farmacias/$id'
    | '/gestores'
    | '/login'
    | '/relatorios'
    | '/setup'
  fileRoutesById: FileRoutesById
}

export interface FarmaciasRouteChildren {
  FarmaciasIndexRoute: typeof FarmaciasIndexRoute
  FarmaciasIdRoute: typeof FarmaciasIdRoute
}

const FarmaciasRouteChildren: FarmaciasRouteChildren = {
  FarmaciasIndexRoute: FarmaciasIndexRoute,
  FarmaciasIdRoute: FarmaciasIdRoute,
}

const FarmaciasRouteWithChildren = FarmaciasRoute._addFileChildren(FarmaciasRouteChildren)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomacoesRoute: typeof AutomacoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FarmaciasRoute: typeof FarmaciasRouteWithChildren
  GestoresRoute: typeof GestoresRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores': {
      id: '/gestores'
      path: '/gestores'
      fullPath: '/gestores'
      preLoaderRoute: typeof GestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias': {
      id: '/farmacias'
      path: '/farmacias'
      fullPath: '/farmacias'
      preLoaderRoute: typeof FarmaciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias/': {
      id: '/farmacias/'
      path: '/'
      fullPath: '/farmacias/'
      preLoaderRoute: typeof FarmaciasIndexRouteImport
      parentRoute: typeof FarmaciasRouteImport
    }
    '/farmacias/$id': {
      id: '/farmacias/$id'
      path: '/$id'
      fullPath: '/farmacias/$id'
      preLoaderRoute: typeof FarmaciasIdRouteImport
      parentRoute: typeof FarmaciasRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomacoesRoute: AutomacoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FarmaciasRoute: FarmaciasRouteWithChildren,
  GestoresRoute: GestoresRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
