/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RankingGestoresRouteImport } from './routes/ranking-gestores'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as OfertasClientesRouteImport } from './routes/ofertas-clientes'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as GestoresRouteImport } from './routes/gestores'
import { Route as FarmaciasRouteImport } from './routes/farmacias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as BancoImagensRouteImport } from './routes/banco-imagens'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as AcoesRouteImport } from './routes/acoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReunioesIndexRouteImport } from './routes/reunioes.index'
import { Route as FarmaciasIndexRouteImport } from './routes/farmacias.index'
import { Route as AcoesIndexRouteImport } from './routes/acoes.index'
import { Route as ReunioesGerenciadorRouteImport } from './routes/reunioes.gerenciador'
import { Route as OfertasTokenRouteImport } from './routes/ofertas.$token'
import { Route as FarmaciasEntradaRouteImport } from './routes/farmacias.entrada'
import { Route as FarmaciasIdRouteImport } from './routes/farmacias.$id'
import { Route as CampanhasNovaRouteImport } from './routes/campanhas.nova'
import { Route as AcoesIdRouteImport } from './routes/acoes.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingGestoresRoute = RankingGestoresRouteImport.update({
  id: '/ranking-gestores',
  path: '/ranking-gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasClientesRoute = OfertasClientesRouteImport.update({
  id: '/ofertas-clientes',
  path: '/ofertas-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresRoute = GestoresRouteImport.update({
  id: '/gestores',
  path: '/gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasRoute = FarmaciasRouteImport.update({
  id: '/farmacias',
  path: '/farmacias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoImagensRoute = BancoImagensRouteImport.update({
  id: '/banco-imagens',
  path: '/banco-imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesRoute = AcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesIndexRoute = ReunioesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReunioesRoute,
} as any)
const FarmaciasIndexRoute = FarmaciasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmaciasRoute,
} as any)
const AcoesIndexRoute = AcoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcoesRoute,
} as any)
const ReunioesGerenciadorRoute = ReunioesGerenciadorRouteImport.update({
  id: '/gerenciador',
  path: '/gerenciador',
  getParentRoute: () => ReunioesRoute,
} as any)
const OfertasTokenRoute = OfertasTokenRouteImport.update({
  id: '/ofertas/$token',
  path: '/ofertas/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasEntradaRoute = FarmaciasEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => FarmaciasRoute,
} as any)
const FarmaciasIdRoute = FarmaciasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FarmaciasRoute,
} as any)
const CampanhasNovaRoute = CampanhasNovaRouteImport.update({
  id: '/campanhas/nova',
  path: '/campanhas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesIdRoute = AcoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRouteWithChildren
  '/anuncios': typeof AnunciosRoute
  '/banco-imagens': typeof BancoImagensRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasRouteWithChildren
  '/gestores': typeof GestoresRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/ofertas-clientes': typeof OfertasClientesRoute
  '/ranking': typeof RankingRoute
  '/ranking-gestores': typeof RankingGestoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/setup': typeof SetupRoute
  '/acoes/$id': typeof AcoesIdRoute
  '/campanhas/nova': typeof CampanhasNovaRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/farmacias/entrada': typeof FarmaciasEntradaRoute
  '/ofertas/$token': typeof OfertasTokenRoute
  '/reunioes/gerenciador': typeof ReunioesGerenciadorRoute
  '/acoes/': typeof AcoesIndexRoute
  '/farmacias/': typeof FarmaciasIndexRoute
  '/reunioes/': typeof ReunioesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/banco-imagens': typeof BancoImagensRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gestores': typeof GestoresRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/ofertas-clientes': typeof OfertasClientesRoute
  '/ranking': typeof RankingRoute
  '/ranking-gestores': typeof RankingGestoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/acoes/$id': typeof AcoesIdRoute
  '/campanhas/nova': typeof CampanhasNovaRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/farmacias/entrada': typeof FarmaciasEntradaRoute
  '/ofertas/$token': typeof OfertasTokenRoute
  '/reunioes/gerenciador': typeof ReunioesGerenciadorRoute
  '/acoes': typeof AcoesIndexRoute
  '/farmacias': typeof FarmaciasIndexRoute
  '/reunioes': typeof ReunioesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRouteWithChildren
  '/anuncios': typeof AnunciosRoute
  '/banco-imagens': typeof BancoImagensRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/farmacias': typeof FarmaciasRouteWithChildren
  '/gestores': typeof GestoresRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/ofertas-clientes': typeof OfertasClientesRoute
  '/ranking': typeof RankingRoute
  '/ranking-gestores': typeof RankingGestoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/setup': typeof SetupRoute
  '/acoes/$id': typeof AcoesIdRoute
  '/campanhas/nova': typeof CampanhasNovaRoute
  '/farmacias/$id': typeof FarmaciasIdRoute
  '/farmacias/entrada': typeof FarmaciasEntradaRoute
  '/ofertas/$token': typeof OfertasTokenRoute
  '/reunioes/gerenciador': typeof ReunioesGerenciadorRoute
  '/acoes/': typeof AcoesIndexRoute
  '/farmacias/': typeof FarmaciasIndexRoute
  '/reunioes/': typeof ReunioesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoes'
    | '/anuncios'
    | '/banco-imagens'
    | '/conexoes'
    | '/configuracoes'
    | '/farmacias'
    | '/gestores'
    | '/grupos'
    | '/login'
    | '/novidades'
    | '/ofertas-clientes'
    | '/ranking'
    | '/ranking-gestores'
    | '/relatorios'
    | '/reunioes'
    | '/setup'
    | '/acoes/$id'
    | '/campanhas/nova'
    | '/farmacias/$id'
    | '/farmacias/entrada'
    | '/ofertas/$token'
    | '/reunioes/gerenciador'
    | '/acoes/'
    | '/farmacias/'
    | '/reunioes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncios'
    | '/banco-imagens'
    | '/conexoes'
    | '/configuracoes'
    | '/gestores'
    | '/grupos'
    | '/login'
    | '/novidades'
    | '/ofertas-clientes'
    | '/ranking'
    | '/ranking-gestores'
    | '/relatorios'
    | '/setup'
    | '/acoes/$id'
    | '/campanhas/nova'
    | '/farmacias/$id'
    | '/farmacias/entrada'
    | '/ofertas/$token'
    | '/reunioes/gerenciador'
    | '/acoes'
    | '/farmacias'
    | '/reunioes'
  id:
    | '__root__'
    | '/'
    | '/acoes'
    | '/anuncios'
    | '/banco-imagens'
    | '/conexoes'
    | '/configuracoes'
    | '/farmacias'
    | '/gestores'
    | '/grupos'
    | '/login'
    | '/novidades'
    | '/ofertas-clientes'
    | '/ranking'
    | '/ranking-gestores'
    | '/relatorios'
    | '/reunioes'
    | '/setup'
    | '/acoes/$id'
    | '/campanhas/nova'
    | '/farmacias/$id'
    | '/farmacias/entrada'
    | '/ofertas/$token'
    | '/reunioes/gerenciador'
    | '/acoes/'
    | '/farmacias/'
    | '/reunioes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcoesRoute: typeof AcoesRouteWithChildren
  AnunciosRoute: typeof AnunciosRoute
  BancoImagensRoute: typeof BancoImagensRoute
  ConexoesRoute: typeof ConexoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FarmaciasRoute: typeof FarmaciasRouteWithChildren
  GestoresRoute: typeof GestoresRoute
  GruposRoute: typeof GruposRoute
  LoginRoute: typeof LoginRoute
  NovidadesRoute: typeof NovidadesRoute
  OfertasClientesRoute: typeof OfertasClientesRoute
  RankingRoute: typeof RankingRoute
  RankingGestoresRoute: typeof RankingGestoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReunioesRoute: typeof ReunioesRouteWithChildren
  SetupRoute: typeof SetupRoute
  CampanhasNovaRoute: typeof CampanhasNovaRoute
  OfertasTokenRoute: typeof OfertasTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-gestores': {
      id: '/ranking-gestores'
      path: '/ranking-gestores'
      fullPath: '/ranking-gestores'
      preLoaderRoute: typeof RankingGestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas-clientes': {
      id: '/ofertas-clientes'
      path: '/ofertas-clientes'
      fullPath: '/ofertas-clientes'
      preLoaderRoute: typeof OfertasClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores': {
      id: '/gestores'
      path: '/gestores'
      fullPath: '/gestores'
      preLoaderRoute: typeof GestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias': {
      id: '/farmacias'
      path: '/farmacias'
      fullPath: '/farmacias'
      preLoaderRoute: typeof FarmaciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco-imagens': {
      id: '/banco-imagens'
      path: '/banco-imagens'
      fullPath: '/banco-imagens'
      preLoaderRoute: typeof BancoImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes': {
      id: '/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes/': {
      id: '/reunioes/'
      path: '/'
      fullPath: '/reunioes/'
      preLoaderRoute: typeof ReunioesIndexRouteImport
      parentRoute: typeof ReunioesRoute
    }
    '/farmacias/': {
      id: '/farmacias/'
      path: '/'
      fullPath: '/farmacias/'
      preLoaderRoute: typeof FarmaciasIndexRouteImport
      parentRoute: typeof FarmaciasRoute
    }
    '/acoes/': {
      id: '/acoes/'
      path: '/'
      fullPath: '/acoes/'
      preLoaderRoute: typeof AcoesIndexRouteImport
      parentRoute: typeof AcoesRoute
    }
    '/reunioes/gerenciador': {
      id: '/reunioes/gerenciador'
      path: '/gerenciador'
      fullPath: '/reunioes/gerenciador'
      preLoaderRoute: typeof ReunioesGerenciadorRouteImport
      parentRoute: typeof ReunioesRoute
    }
    '/ofertas/$token': {
      id: '/ofertas/$token'
      path: '/ofertas/$token'
      fullPath: '/ofertas/$token'
      preLoaderRoute: typeof OfertasTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias/entrada': {
      id: '/farmacias/entrada'
      path: '/entrada'
      fullPath: '/farmacias/entrada'
      preLoaderRoute: typeof FarmaciasEntradaRouteImport
      parentRoute: typeof FarmaciasRoute
    }
    '/farmacias/$id': {
      id: '/farmacias/$id'
      path: '/$id'
      fullPath: '/farmacias/$id'
      preLoaderRoute: typeof FarmaciasIdRouteImport
      parentRoute: typeof FarmaciasRoute
    }
    '/campanhas/nova': {
      id: '/campanhas/nova'
      path: '/campanhas/nova'
      fullPath: '/campanhas/nova'
      preLoaderRoute: typeof CampanhasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/$id': {
      id: '/acoes/$id'
      path: '/$id'
      fullPath: '/acoes/$id'
      preLoaderRoute: typeof AcoesIdRouteImport
      parentRoute: typeof AcoesRoute
    }
  }
}

interface AcoesRouteChildren {
  AcoesIdRoute: typeof AcoesIdRoute
  AcoesIndexRoute: typeof AcoesIndexRoute
}

const AcoesRouteChildren: AcoesRouteChildren = {
  AcoesIdRoute: AcoesIdRoute,
  AcoesIndexRoute: AcoesIndexRoute,
}

const AcoesRouteWithChildren = AcoesRoute._addFileChildren(AcoesRouteChildren)

interface FarmaciasRouteChildren {
  FarmaciasIdRoute: typeof FarmaciasIdRoute
  FarmaciasEntradaRoute: typeof FarmaciasEntradaRoute
  FarmaciasIndexRoute: typeof FarmaciasIndexRoute
}

const FarmaciasRouteChildren: FarmaciasRouteChildren = {
  FarmaciasIdRoute: FarmaciasIdRoute,
  FarmaciasEntradaRoute: FarmaciasEntradaRoute,
  FarmaciasIndexRoute: FarmaciasIndexRoute,
}

const FarmaciasRouteWithChildren = FarmaciasRoute._addFileChildren(
  FarmaciasRouteChildren,
)

interface ReunioesRouteChildren {
  ReunioesGerenciadorRoute: typeof ReunioesGerenciadorRoute
  ReunioesIndexRoute: typeof ReunioesIndexRoute
}

const ReunioesRouteChildren: ReunioesRouteChildren = {
  ReunioesGerenciadorRoute: ReunioesGerenciadorRoute,
  ReunioesIndexRoute: ReunioesIndexRoute,
}

const ReunioesRouteWithChildren = ReunioesRoute._addFileChildren(
  ReunioesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcoesRoute: AcoesRouteWithChildren,
  AnunciosRoute: AnunciosRoute,
  BancoImagensRoute: BancoImagensRoute,
  ConexoesRoute: ConexoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FarmaciasRoute: FarmaciasRouteWithChildren,
  GestoresRoute: GestoresRoute,
  GruposRoute: GruposRoute,
  LoginRoute: LoginRoute,
  NovidadesRoute: NovidadesRoute,
  OfertasClientesRoute: OfertasClientesRoute,
  RankingRoute: RankingRoute,
  RankingGestoresRoute: RankingGestoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReunioesRoute: ReunioesRouteWithChildren,
  SetupRoute: SetupRoute,
  CampanhasNovaRoute: CampanhasNovaRoute,
  OfertasTokenRoute: OfertasTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
